# ~/.config/starship.toml

add_newline = true
command_timeout = 1000

format = """
$cmd_duration\
$os$hostname\
$directory\
$git_branch\
$git_status \
$python\
$aws\
$golang\
$java\
$nodejs\
$rust\
$ruby\
$scala\
$dart\
$conda\
$pijul_channel\
$lua\
$rlang\
$package\
$buf\
$memory_usage\
$docker_context\
[](#1C3A5E)$time[](#1C3A5E)
$character"""


continuation_prompt = '▶▶ '

[character]
success_symbol = "[└ • 🚀 ](bold fg:green) "
error_symbol = "[└ • 🔥 󰅙](bold fg:red) "
[time]
disabled = false
time_format = "%r" # Hour:Minute Formatx
style = "bg:#1d2230"
format = '[[󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

[cmd_duration]
min_time = 0
format = '[](bold fg:green)[ $duration](bold bg:green fg:black)[](bold fg:green) •• '

[os]
disabled = true

# Shows the hostname
[hostname]
ssh_only = false
format = '[](bold fg:yellow)[$hostname](bold bg:yellow fg:black)[](bold fg:yellow) •• '
disabled = false
ssh_symbol = " "

# Shows current directory
[directory]
truncation_length = 3
fish_style_pwd_dir_length=2
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = '[](bold fg:white)[$path](bold bg:white fg:black)[$read_only](bold bg:white fg:black)[](bold fg:white) ••'

# Shows current git branch
[git_branch]
symbol = " "
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = '🏳'
up_to_date = ''
untracked = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = ' '
modified = ' '
staged = '[++\($count\)](green)'
renamed = '襁 '
deleted = ' '


# ---

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "
disabled = true
style='bold dimmed white'
threshold = 1
format = "$symbol [${ram}(|${swap})]($style) "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true

[ruby]
symbol = " "

[rlang]
symbol = "󰟔 "

[rust]
symbol = " "

[scala]
symbol = " "
